[package]
name = "templates"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
tera = "1"
base64 = "0.12"
lazy_static = "1"
pulldown-cmark = "0.7"
toml = "0.5"
csv = "1"
image = "0.23"
serde_json = "1.0"
sha2 = "0.8"
url = "2"

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library" }
config = { path = "../config" }
imageproc = { path = "../imageproc" }

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["blocking", "rustls-tls"]

[dev-dependencies]
mockito = "0.25"
